name: Deploy Microsite
on:
  push:
    branches:
      - master

jobs:
  deploy-microsite-and-storybook:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
      DOCUSAURUS_SSR_CONCURRENCY: 5

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: use node.js 18.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      # We avoid caching in this workflow, as we're running an install of both the top-level
      # dependencies and the microsite. We leave it to the main master workflow to produce the
      # cache, as that results in a smaller bundle.
      - name: top-level yarn install
        run: yarn install --immutable
      - name: microsite yarn install
        run: yarn install --immutable
        working-directory: microsite
      - name: storybook yarn install
        run: yarn install --immutable
        working-directory: storybook

      - name: build API reference
        run: yarn build:api-docs

      - name: build microsite
        run: yarn build
        working-directory: microsite

      - name: build storybook
        run: yarn build-storybook
        working-directory: storybook

      - name: move storybook dist into microsite
        run: mv storybook/dist/ microsite/build/storybook

      - name: Check the build output
        run: ls microsite/build && ls microsite/build/storybook

      - name: Deploy both microsite and storybook to gh-pages
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc # v4.4.3
        with:
          branch: gh-pages
          folder: microsite/build
