name: Issue
on:
  issues:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest

    if: github.repository == 'backstage/backstage'
    steps:
      - name: Issue sync
        uses: backstage/actions/issue-sync@497722d45fb5a35c14c721f63ed74e6ad5f629dd # v0.6.4
